FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04

# Install git, wget, bc and dependencies
RUN apt-get update && apt-get install -y \
    git \
    iproute2 \
    wget \
    python3.5 \
    python3-pip \
    python3-dev \
    libmysqlclient-dev \
    cmake
RUN apt-get install -y --allow-downgrades --no-install-recommends \
  libcudnn7=7.0.5.15-1+cuda9.0 libcudnn7-dev=7.0.5.15-1+cuda9.0 && rm -rf /var/lib/apt/lists/*

# opencv3 install
RUN apt-get update && apt-get install -y zip tar curl cmake libavcodec-dev libavformat-dev libswscale-dev libv4l-dev libatlas-base-dev gfortran libgtk2.0-dev
RUN wget https://github.com/Itseez/opencv/archive/3.4.0.zip && unzip 3.4.0.zip
WORKDIR /opencv-3.4.0/build
RUN cmake .. \
  -D CMAKE_BUILD_TYPE=RELEASE \
  -D CMAKE_INSTALL_PREFIX=/usr/local \
  -D BUILD_opencv_java=OFF \
  -D WITH_IPP=OFF \
  -D PYTHON_EXECUTABLE=/usr/bin/python3.4 .. \
 && make -j4 \
 && make install

ADD requirements.txt ./
RUN pip3 install -r requirements.txt
RUN pip3 install tensorflow-gpu==1.3.0

RUN mkdir -p /root/.config/matplotlib
RUN echo "backend : Agg" > /root/.config/matplotlib/matplotlibrc

WORKDIR /code

CMD [ "python", "src/test.py" ]
