FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

# Install git, wget, bc and dependencies
RUN apt-get update && apt-get install -y \
    git \
    iproute2 \
    wget \
    python3.5 \
    python3-pip \
    python3-dev \
    libmysqlclient-dev \
    cmake
RUN apt-get install -y --allow-downgrades --no-install-recommends \
  libcudnn7=7.0.5.15-1+cuda9.0 libcudnn7-dev=7.0.5.15-1+cuda9.0 && rm -rf /var/lib/apt/lists/*

ADD requirements.txt ./
RUN pip3 install -r requirements.txt
RUN pip3 install tensorflow-gpu

RUN mkdir -p /root/.config/matplotlib
RUN echo "backend : Agg" > /root/.config/matplotlib/matplotlibrc

WORKDIR /code

CMD [ "python", "src/test.py" ]
